# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NaN
email: hi@ponan.li
locale: zh_TW
description: >- # this means to ignore newlines until "baseurl:"
  NaN is not a number
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.ponan.li" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
permalink: 'post/:year/:month/:day/:title/'
github_username:  leeneil
disqus_shortname: notanumber
analytics: UA-42052947-1

# Build settings
markdown: kramdown
# markdown: redcarpet
theme: jekyll-theme-minimal
# plugins:
#  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-paginate

#paginate: 10
#paginate_path: ":num"

#defaults:
#  - scope:
#      path: "assets/img"
#    values:
#      image: true

#exclude:
#    - node_modules

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
